version: 3.1
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./banco:/data/db
    environment:
      MONGO_INITDB_DATABASE: petManange
    ports:
      - 27017:27017
  backend:
    image: node:12
    volumes:
        - ./backend:./backend
      ports:
        - 3000:3000
      depends_on:
        - mongodb
      command: bash -c "cd backend && npm i && npm run dev"
  frontend:
    image: node:12
    volumes:
      - ./frontEnd:/frontEnd
    ports:
      - 8080:8080
    depends_on:
      - backend
      command: bash -c "cd frontEnd && npm i && npm run serve"